kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - port: 1
---
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: XXXXX
    ports:
      - port: 1
  - addresses:
      - ip: XXXXX
    ports:
      - port: 1
